### ISSUE TITLE
Add README.md.meta to avoid Unity error message

### ISSUE THREAD

**Issue by KonajuGames** [Cratesmith/cratesmith.enums#1]
Unity reports this error message twice on the next load of the project after importing the package.

![image](https://user-images.githubusercontent.com/694943/160723768-d306bd74-1205-4262-aa7b-cf13cc7f26a4.png)

Unity cannot add the meta file because the repo has been cloned to Unity's separate managed package area. Add a meta file to the repo to prevent this error.

**Comment by Cratesmith** [comment]
Added the file, I'm not sure if you'll be able to just update the package or if you'll need to add/remove it in the package manager to get the new version. Let me know how it goes

**Comment by KonajuGames** [comment]
It will need a remove and re-add because the package.json wasn't updated with a new version number.

**Comment by Cratesmith** [comment]
hmm ok,
I'll update it in a bit. I do wonder if the git packages actually respect version numbers. They didn't seem to a while back.

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------
